### ISSUE TITLE
Fix tower overwriting

### ISSUE THREAD

**Issue by jonathan-fong** [jonathan-fong/Toontown_Tower_Defense#8]
Current version can replace an existing tower.

**Comment by brianzhang01** [comment]
Hmm, I'm not sure why this didn't automatically close the issue. We can look into it together.

**Comment by brianzhang01** [comment]
Oh I see, the word "Fixed" needs to be immediately followed by the issue number, so you should just say "Fixes #8". https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
